-- 执行行记录TM调用意图和恢复进度；COMMIT/ROLLBACK字段不是全局权威decision。
CREATE TABLE allocation_execution (
    enterprise_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '企业隔离范围',
    attempt_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原固定参与者attempt',
    fulfillment_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原履约单',
    command_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '首次执行命令键',
    actor_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '首次授权执行的主体',
    payload_hash CHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '冻结Try请求及TC来源的规范摘要',
    try_payload JSON NOT NULL COMMENT '固定仓/货主/库位/批次/数量/路由的V1请求清单',
    cluster_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原TC集群，重启不可换环境',
    transaction_group VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT '原TM事务分组',
    launch_owner CHAR(36) COLLATE utf8mb4_bin NOT NULL COMMENT '持久化启动身份，不使用重启后的进程ID',
    xid VARCHAR(128) COLLATE utf8mb4_bin NULL COMMENT '已知原XID，不允许重新begin替换',
    empty_xid BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'begin返回但attempt绑定失败的已知空XID',
    state VARCHAR(32) COLLATE utf8mb4_bin NOT NULL DEFAULT 'READY' COMMENT '执行阶段，不代替TC终态证据',
    requested_action VARCHAR(8) COLLATE utf8mb4_bin NULL COMMENT '一次固定的COMMIT或ROLLBACK调用意图',
    next_warehouse INT NOT NULL DEFAULT 0 COMMENT '已保存原Try回执的仓数量',
    rpc_attempts INT NOT NULL DEFAULT 0 COMMENT '当前阶段外部请求次数，有界重试',
    claim_epoch BIGINT NOT NULL DEFAULT 0 COMMENT '每次领取递增代际，拒绝旧执行器回写',
    lease_until DATETIME(6) NULL COMMENT '当前单步执行租约截止UTC时刻',
    next_at DATETIME(6) NOT NULL COMMENT '下次允许恢复UTC时刻',
    error_code VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '脱敏恢复原因码',
    terminal_evidence JSON NULL COMMENT '只读TC审计取得的原XID终态证据',
    created_at DATETIME(6) NOT NULL COMMENT '首次受理UTC时间',
    updated_at DATETIME(6) NOT NULL COMMENT '最后推进UTC时间',
    PRIMARY KEY (enterprise_id,attempt_id),
    UNIQUE KEY uk_execution_command (enterprise_id,command_id),
    UNIQUE KEY uk_execution_xid (xid),
    KEY idx_execution_due (enterprise_id,next_at,attempt_id),
    CONSTRAINT ck_execution_state CHECK(state IN ('READY','BEGIN_CALLING','BEGIN_UNKNOWN','TRYING','FINISH_REQUESTED','WAITING_TERMINAL','COMPLETED','ROLLED_BACK','ISOLATED')),
    CONSTRAINT ck_execution_action CHECK(requested_action IS NULL OR requested_action IN ('COMMIT','ROLLBACK')),
    CONSTRAINT ck_execution_bounds CHECK(next_warehouse BETWEEN 0 AND 200 AND rpc_attempts BETWEEN 0 AND 8 AND claim_epoch>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='固定attempt的持久化TM执行进度及不可变请求意图';
