service {
  vgroupMapping.wms_inventory_group = "default"
  default.grouplist = "seata-server:8091"
  enableDegrade = false
  disableGlobalTransaction = false
}
client {
  tm {
    commitRetryCount = 5
    rollbackRetryCount = 5
  }
}
