-- S2-04a 库存命令、凭证、执行授权与占用。入出库 source_command/inbox 在各自服务迁移。

CREATE TABLE stock_command (
  id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '不透明commandId，与command_id相同',
  enterprise_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '企业权限范围',
  warehouse_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '仓库及路由键',
  source_service VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '来源服务稳定编码',
  command_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '来源命令身份',
  action VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT '动作稳定编码',
  business_effect_key VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '库存效果业务键',
  execution_attempt_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '本命令执行尝试',
  attempt_no BIGINT NOT NULL COMMENT '效果内尝试序号，从1起',
  previous_command_id VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '安全关闭所依据的上一命令，首次可空',
  payload_digest CHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '不可变请求SHA-256十六进制',
  digest_version INT NOT NULL COMMENT '摘要规范版本',
  state VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT '命令状态稳定编码',
  settlement_digest CHAR(64) COLLATE utf8mb4_bin NULL COMMENT '结案摘要，未结案可空',
  result_json JSON NULL COMMENT '确定结果快照，未结案可空',
  compensates_command_id VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '补偿所针对的原命令，非补偿可空',
  safe_close_id VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '安全关闭证据标识，未关闭可空',
  safe_close_version BIGINT NOT NULL DEFAULT 0 COMMENT '安全关闭证据版本',
  safe_close_evidence JSON NULL COMMENT '安全关闭证据正文，未关闭可空',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '并发版本',
  created_at DATETIME(6) NOT NULL COMMENT 'UTC创建时刻',
  updated_at DATETIME(6) NOT NULL COMMENT 'UTC最后变更时刻',
  PRIMARY KEY (id),
  UNIQUE KEY uk_stock_command_id (enterprise_id, warehouse_id, source_service, command_id),
  UNIQUE KEY uk_stock_command_attempt (enterprise_id, warehouse_id, source_service, business_effect_key, action, attempt_no),
  KEY idx_stock_command_effect (enterprise_id, warehouse_id, source_service, business_effect_key, action, state),
  CONSTRAINT ck_stock_command_id CHECK (id = command_id),
  CONSTRAINT ck_stock_command_attempt CHECK (attempt_no >= 1 AND digest_version >= 1 AND safe_close_version >= 0 AND version >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存命令占位与取消墓碑，与效果凭证同物理事务';

CREATE TABLE stock_posting (
  id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '库存凭证标识',
  enterprise_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '企业权限范围',
  warehouse_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '仓库及路由键',
  source_service VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '来源服务稳定编码',
  command_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '产生该凭证的命令',
  business_effect_key VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '库存效果业务键',
  action VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT '动作稳定编码',
  execution_attempt_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '过账对应的执行尝试',
  posting_type VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT '凭证类型稳定编码',
  quantity DECIMAL(20,6) NOT NULL COMMENT '过账数量，符号由类型解释',
  source_execution_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '来源实物事实引用，无来源时用固定非空标识',
  source_document_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '来源单据引用',
  ledger_manifest JSON NOT NULL COMMENT '同事务流水清单',
  result_version BIGINT NOT NULL COMMENT '凭证结果版本',
  original_posting_id VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '被逆向的原凭证，正向可空',
  reversed_qty DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '已被后续逆向消耗的数量',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '并发版本',
  created_at DATETIME(6) NOT NULL COMMENT 'UTC创建时刻',
  updated_at DATETIME(6) NOT NULL COMMENT 'UTC最后变更时刻',
  PRIMARY KEY (id),
  UNIQUE KEY uk_stock_posting_command (enterprise_id, warehouse_id, source_service, command_id),
  UNIQUE KEY uk_stock_posting_effect (enterprise_id, warehouse_id, source_service, business_effect_key, action),
  CONSTRAINT ck_stock_posting_qty CHECK (quantity >= 0 AND reversed_qty >= 0 AND reversed_qty <= quantity),
  CONSTRAINT ck_stock_posting_version CHECK (result_version >= 0 AND version >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存过账凭证，一效果一有效最终凭证';

CREATE TABLE execution_permit (
  id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '不透明permitId，与permit_id相同',
  enterprise_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '企业权限范围',
  warehouse_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '仓库及路由键',
  source_service VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '来源服务稳定编码',
  permit_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '执行授权身份',
  command_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '绑定的库存命令',
  business_effect_key VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '库存效果业务键',
  execution_attempt_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '授权对应的执行尝试',
  attempt_no BIGINT NOT NULL COMMENT '效果内尝试序号',
  source_task_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '来源任务身份',
  source_task_epoch BIGINT NOT NULL COMMENT '来源任务代际',
  gate_epoch BIGINT NOT NULL COMMENT '签发时门禁代际',
  action VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT '授权动作稳定编码',
  payload_digest CHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '授权意图SHA-256十六进制',
  quantity DECIMAL(20,6) NOT NULL COMMENT '授权数量上限',
  actual_qty DECIMAL(20,6) NULL COMMENT '已确认执行量，未结案可空',
  not_executed_qty DECIMAL(20,6) NULL COMMENT '确定未执行量，未结案可空',
  settlement_digest CHAR(64) COLLATE utf8mb4_bin NULL COMMENT '结案摘要，未结案可空',
  state VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT '授权状态稳定编码',
  started_at DATETIME(6) NULL COMMENT '开始执行UTC时刻，未开始可空',
  posted_at DATETIME(6) NULL COMMENT '过账UTC时刻，未过账可空',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '并发版本',
  created_at DATETIME(6) NOT NULL COMMENT 'UTC创建时刻',
  updated_at DATETIME(6) NOT NULL COMMENT 'UTC最后变更时刻',
  PRIMARY KEY (id),
  UNIQUE KEY uk_execution_permit_id (enterprise_id, warehouse_id, permit_id),
  UNIQUE KEY uk_execution_permit_command (enterprise_id, warehouse_id, source_service, command_id),
  CONSTRAINT ck_permit_id CHECK (id = permit_id),
  CONSTRAINT ck_permit_qty CHECK (quantity >= 0 AND attempt_no >= 1 AND source_task_epoch >= 0 AND gate_epoch >= 0 AND version >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='实物执行授权，未证实未执行不得TTL回收';

CREATE TABLE execution_claim (
  id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '执行占用明细标识',
  enterprise_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '企业权限范围',
  warehouse_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '仓库及路由键',
  permit_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '所属执行授权',
  balance_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '占用的库存桶',
  reservation_line_id VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '已预占拣发明细，自由占用可空',
  serial_id VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '占用的序列号，非序列号可空',
  claim_type VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT '占用类型稳定编码',
  quantity DECIMAL(20,6) NOT NULL COMMENT '占用数量',
  state VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT '占用状态稳定编码',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '并发版本',
  created_at DATETIME(6) NOT NULL COMMENT 'UTC创建时刻',
  updated_at DATETIME(6) NOT NULL COMMENT 'UTC最后变更时刻',
  PRIMARY KEY (id),
  KEY idx_execution_claim_permit (enterprise_id, warehouse_id, permit_id),
  KEY idx_execution_claim_balance (enterprise_id, warehouse_id, balance_id, state),
  CONSTRAINT ck_execution_claim_qty CHECK (quantity >= 0 AND version >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='执行占用明细，库存事务锁桶仲裁不得只靠可空唯一键';
