-- 同仓移库单据、库存限制与独立调整。限制不是盘点门禁，调整不是 count_plan 行。

CREATE TABLE warehouse_move (
  id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '移库单据标识',
  enterprise_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '企业权限范围',
  warehouse_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '仓库及路由键',
  client_operation_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '与 Idempotency-Key 一致',
  source_balance_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '移出库存桶',
  target_location_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '移入库位',
  target_balance_id VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '移入后目标桶，未过账可空',
  qty DECIMAL(20,6) NOT NULL COMMENT '移库数量',
  unit VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT '单位',
  reason VARCHAR(128) COLLATE utf8mb4_bin NOT NULL COMMENT '移库原因',
  actor_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '提交人',
  operation_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '库存操作标识',
  state VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT '单据状态：ACCEPTED',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '并发版本',
  created_at DATETIME(6) NOT NULL COMMENT 'UTC创建时刻',
  updated_at DATETIME(6) NOT NULL COMMENT 'UTC最后变更时刻',
  PRIMARY KEY (id),
  UNIQUE KEY uk_warehouse_move_op (enterprise_id, warehouse_id, client_operation_id),
  KEY idx_warehouse_move_src (enterprise_id, warehouse_id, source_balance_id),
  CONSTRAINT ck_warehouse_move_qty CHECK (qty > 0 AND version >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='同仓移库单据，过账走库存内核';

CREATE TABLE stock_hold (
  id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '库存限制标识',
  enterprise_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '企业权限范围',
  warehouse_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '仓库及路由键',
  client_operation_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '与 Idempotency-Key 一致',
  balance_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '限制的库存桶',
  location_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '库位，供重叠判断',
  sku_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品',
  lot_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '批次，无批次用 NO_LOT',
  qty DECIMAL(20,6) NOT NULL COMMENT '限制数量，计入 reserved',
  reason VARCHAR(128) COLLATE utf8mb4_bin NOT NULL COMMENT '限制原因',
  evidence_refs JSON NULL COMMENT '证据引用，无可空',
  actor_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '创建人',
  released_by VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '释放人，未释放可空',
  release_reason VARCHAR(128) COLLATE utf8mb4_bin NULL COMMENT '释放原因，未释放可空',
  operation_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '占用库存操作',
  release_operation_id VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '释放库存操作，未释放可空',
  state VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT 'OPEN 或 RELEASED',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '并发版本',
  created_at DATETIME(6) NOT NULL COMMENT 'UTC创建时刻',
  updated_at DATETIME(6) NOT NULL COMMENT 'UTC最后变更时刻',
  PRIMARY KEY (id),
  UNIQUE KEY uk_stock_hold_op (enterprise_id, warehouse_id, client_operation_id),
  KEY idx_stock_hold_balance (enterprise_id, warehouse_id, balance_id, state),
  CONSTRAINT ck_stock_hold_qty CHECK (qty > 0 AND version >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存限制，与盘点 location_gate 分离，可重叠';

CREATE TABLE warehouse_adjustment (
  id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '独立调整单标识',
  enterprise_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '企业权限范围',
  warehouse_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '仓库及路由键',
  client_operation_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '创建幂等键',
  count_line_id VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '可选关联盘点行，不是盘点调整本身',
  balance_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '调整的库存桶',
  delta_qty DECIMAL(20,6) NOT NULL COMMENT '实物增量，可负',
  reason VARCHAR(128) COLLATE utf8mb4_bin NOT NULL COMMENT '调整原因',
  evidence_refs JSON NULL COMMENT '证据引用，无可空',
  actor_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '创建人',
  decision VARCHAR(32) COLLATE utf8mb4_bin NULL COMMENT 'APPROVED 或 REJECTED，未审可空',
  decided_by VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '审批人，未审可空',
  decision_reason VARCHAR(128) COLLATE utf8mb4_bin NULL COMMENT '审批意见，未审可空',
  apply_operation_id VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '过账操作，未应用可空',
  state VARCHAR(32) COLLATE utf8mb4_bin NOT NULL COMMENT 'DRAFT/APPROVED/REJECTED/APPLIED',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '并发版本',
  created_at DATETIME(6) NOT NULL COMMENT 'UTC创建时刻',
  updated_at DATETIME(6) NOT NULL COMMENT 'UTC最后变更时刻',
  PRIMARY KEY (id),
  UNIQUE KEY uk_warehouse_adjustment_op (enterprise_id, warehouse_id, client_operation_id),
  KEY idx_warehouse_adjustment_wh (enterprise_id, warehouse_id, id),
  CONSTRAINT ck_warehouse_adjustment_ver CHECK (version >= 0 AND delta_qty <> 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='仓级独立调整，不是 count_plan 应用行';
