CREATE TABLE inventory_tcc_intent (
    id VARCHAR(36) NOT NULL COMMENT '登记前持久化意图标识',
    enterprise_id VARCHAR(64) NOT NULL COMMENT '企业隔离范围',
    warehouse_id VARCHAR(64) NOT NULL COMMENT '原固定参与仓',
    allocation_id VARCHAR(64) NOT NULL COMMENT '履约分配标识',
    attempt_id VARCHAR(64) NOT NULL COMMENT '原尝试标识',
    xid VARCHAR(128) NOT NULL COMMENT '原TC全局事务，不可改绑',
    action_name VARCHAR(128) NOT NULL COMMENT '固定集群与cell资源身份',
    cell_id VARCHAR(64) NOT NULL COMMENT '原物理cell',
    route_epoch BIGINT NOT NULL COMMENT 'Try时明确仓路由代际',
    request_digest CHAR(64) NOT NULL COMMENT '服务端计算的规范化原始请求摘要',
    request_payload JSON NOT NULL COMMENT '原始V1仓级Try完整事实',
    branch_id BIGINT NULL COMMENT 'TC登记应答或原TC回调确认的分支；NULL不允许盲目重新登记',
    reservation_id VARCHAR(36) NULL COMMENT '与Try事务一起绑定的库存预占',
    state VARCHAR(24) NOT NULL COMMENT 'REGISTERING/REGISTERED/TRIED/CONFIRMED/CANCELLED',
    created_at DATETIME(6) NOT NULL COMMENT 'UTC意图建立时间',
    updated_at DATETIME(6) NOT NULL COMMENT 'UTC最新持久化时间',
    PRIMARY KEY(id),
    UNIQUE KEY uk_tcc_attempt(enterprise_id,warehouse_id,allocation_id,attempt_id),
    UNIQUE KEY uk_tcc_branch(xid,branch_id),
    KEY idx_tcc_warehouse_state(enterprise_id,warehouse_id,state,created_at),
    CONSTRAINT ck_tcc_intent_epoch CHECK(route_epoch>0),
    CONSTRAINT ck_tcc_intent_branch CHECK(branch_id IS NULL OR branch_id>0),
    CONSTRAINT ck_tcc_intent_state CHECK(state IN ('REGISTERING','REGISTERED','TRIED','CONFIRMED','CANCELLED'))
) COMMENT='真实RM登记与Try恢复意图；登记结果未知保持原XID';
