-- 逐身份远程结果先持久化，整行本地事务仅消费已核验凭证，不持有网络调用。
CREATE TABLE count_adjustment_intent (
  id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原盘点行调整稳定标识',
  enterprise_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '企业权限范围',
  warehouse_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '仓路由范围',
  plan_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原已审批计划',
  line_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原盘点快照行',
  observation_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '审批时最新完整观察',
  operation_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '首次调整操作，后台沿用不另造命令',
  actor_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '首次调整主体',
  context_json JSON NOT NULL COMMENT '原桶、数量、观察和身份快照，V1不可变',
  context_hash CHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原完整调整输入摘要',
  state VARCHAR(16) COLLATE utf8mb4_bin NOT NULL COMMENT 'PENDING、READY或APPLIED',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '进度并发版本',
  created_at DATETIME(6) NOT NULL COMMENT '原调整创建UTC时刻',
  updated_at DATETIME(6) NOT NULL COMMENT '最后进度UTC时刻',
  PRIMARY KEY(id),
  UNIQUE KEY uk_count_adjustment_line(enterprise_id,warehouse_id,line_id),
  KEY idx_count_adjustment_plan(enterprise_id,warehouse_id,plan_id,state,id),
  CONSTRAINT ck_count_adjustment_state CHECK(state IN ('PENDING','READY','APPLIED')),
  CONSTRAINT ck_count_adjustment_version CHECK(version>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='序列盘点逐行不可变调整上下文及本地应用屏障';
CREATE TABLE count_serial_intent (
  id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原调整及序列号的稳定恢复标识',
  enterprise_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '企业权限范围',
  warehouse_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '仓路由范围',
  adjustment_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原盘点行调整',
  plan_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原审批计划',
  serial_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '规范化序列号',
  sku_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原SKU身份',
  operation_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原调整操作，网络重试固定',
  kind VARCHAR(16) COLLATE utf8mb4_bin NOT NULL COMMENT 'FOUND或MISSING',
  from_epoch BIGINT NULL COMMENT '原本地归属代际，全新盘盈为空',
  state VARCHAR(16) COLLATE utf8mb4_bin NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING、RUNNING、DONE或ISOLATED',
  result_json JSON NULL COMMENT '已核对原范围和操作的登记结果，不用旧响应重新授权',
  claim_epoch BIGINT NOT NULL DEFAULT 0 COMMENT '领取代际，防止旧执行器完成',
  attempts INT NOT NULL DEFAULT 0 COMMENT '自动尝试次数，最多12次',
  next_attempt_at DATETIME(6) NOT NULL COMMENT '下次重试或租约截止UTC',
  last_error VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '稳定错误码',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '进度并发版本',
  created_at DATETIME(6) NOT NULL COMMENT '原身份调整创建UTC时刻',
  updated_at DATETIME(6) NOT NULL COMMENT '最后进度UTC时刻',
  PRIMARY KEY(id),
  UNIQUE KEY uk_count_serial_fact(enterprise_id,warehouse_id,adjustment_id,serial_id),
  KEY idx_count_serial_ready(enterprise_id,warehouse_id,plan_id,state,next_attempt_at,id),
  KEY idx_count_serial_list(enterprise_id,warehouse_id,created_at,id),
  CONSTRAINT ck_count_serial_kind CHECK ((kind='MISSING' AND from_epoch IS NOT NULL AND from_epoch>=0) OR (kind='FOUND' AND (from_epoch IS NULL OR from_epoch>=0))),
  CONSTRAINT ck_count_serial_progress CHECK (claim_epoch>=0 AND attempts BETWEEN 0 AND 12 AND version>=0),
  CONSTRAINT ck_count_serial_result CHECK ((state='DONE' AND result_json IS NOT NULL) OR (state IN ('PENDING','RUNNING','ISOLATED') AND result_json IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='盘点逐序列号登记结果及有界恢复，不等于库存调整已提交';
