CREATE TABLE serial_shipment_intent (
 id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原发运命令与SN稳定事实标识',
 enterprise_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '企业范围',
 warehouse_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '实际发运仓',
 command_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原来源SHIP命令',
 serial_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '规范化实物SN',
 sku_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原商品',
 pick_fact_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原预占订单行的具体拣货事实',
 balance_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '实际扣减暂存桶',
 shipment_ref VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '已提交库存发运流水操作引用',
 owner_epoch BIGINT NOT NULL COMMENT '实际扣减身份的原代际',
 state VARCHAR(16) COLLATE utf8mb4_bin NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING、RUNNING、DONE或ISOLATED',
 result_json JSON NULL COMMENT '匹配原事实的登记证明，只在DONE保存',
 claim_epoch BIGINT NOT NULL DEFAULT 0 COMMENT '领取代际，防止旧执行器覆盖',
 attempts INT NOT NULL DEFAULT 0 COMMENT '当前人工重试周期自动次数，上限12',
 next_attempt_at DATETIME(6) NOT NULL COMMENT '退避或租约截止UTC',
 last_error VARCHAR(64) COLLATE utf8mb4_bin NULL COMMENT '最近失败错误码',
 version BIGINT NOT NULL DEFAULT 0 COMMENT '进度版本',
 created_at DATETIME(6) NOT NULL COMMENT '实际本地发运提交UTC',
 updated_at DATETIME(6) NOT NULL COMMENT '登记进度更新UTC',
 PRIMARY KEY(id),
 UNIQUE KEY uk_serial_shipment_command(enterprise_id,warehouse_id,command_id,serial_id),
 UNIQUE KEY uk_serial_shipment_identity(enterprise_id,warehouse_id,sku_id,serial_id,owner_epoch),
 KEY idx_serial_shipment_ready(enterprise_id,warehouse_id,state,next_attempt_at,id),
 KEY idx_serial_shipment_list(enterprise_id,warehouse_id,created_at,id),
 CONSTRAINT ck_serial_shipment_counters CHECK(owner_epoch>=0 AND claim_epoch>=0 AND attempts BETWEEN 0 AND 12 AND version>=0),
 CONSTRAINT ck_serial_shipment_result CHECK((state='DONE' AND result_json IS NOT NULL) OR (state IN ('PENDING','RUNNING','ISOLATED') AND result_json IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='原发运扣减与身份离库同事务产生的登记意图，不能重放数量';
