#!/bin/bash
# 应用库、Seata 会话库与 XXL 调度库分账号；仅对本实例授权，不跨 Cell。
set -euo pipefail
: "${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}"
: "${WMS_INBOUND_DB_PASSWORD:?WMS_INBOUND_DB_PASSWORD is required}"
: "${WMS_OUTBOUND_DB_PASSWORD:?WMS_OUTBOUND_DB_PASSWORD is required}"
: "${WMS_SEATA_DB_PASSWORD:?WMS_SEATA_DB_PASSWORD is required}"
: "${WMS_XXL_DB_PASSWORD:?WMS_XXL_DB_PASSWORD is required}"

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS wms_inbound DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS wms_outbound DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS seata DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS xxl_job DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'wms_inbound'@'%' IDENTIFIED BY '${WMS_INBOUND_DB_PASSWORD}';
CREATE USER IF NOT EXISTS 'wms_outbound'@'%' IDENTIFIED BY '${WMS_OUTBOUND_DB_PASSWORD}';
CREATE USER IF NOT EXISTS 'wms_seata'@'%' IDENTIFIED BY '${WMS_SEATA_DB_PASSWORD}';
CREATE USER IF NOT EXISTS 'wms_xxl'@'%' IDENTIFIED BY '${WMS_XXL_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON wms_inbound.* TO 'wms_inbound'@'%';
GRANT ALL PRIVILEGES ON wms_outbound.* TO 'wms_outbound'@'%';
GRANT ALL PRIVILEGES ON seata.* TO 'wms_seata'@'%';
GRANT ALL PRIVILEGES ON xxl_job.* TO 'wms_xxl'@'%';
FLUSH PRIVILEGES;
EOSQL
