CREATE TABLE outbound_serial_pick (
 id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原拣货命令与SN稳定事实标识',
 enterprise_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '企业权限范围',
 warehouse_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '作业仓范围',
 command_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '不可变原PICK命令',
 task_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原拣货任务',
 order_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原出库单',
 document_line_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '来源出库内部行',
 order_line_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原预占业务订单行',
 allocation_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原分配身份',
 attempt_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原分配尝试',
 sku_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原商品',
 serial_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '规范化实物SN',
 owner_epoch BIGINT NOT NULL COMMENT '本次选择归属代际，不能借用旧周期',
 source_location_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原任务拣出库位',
 target_location_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原任务暂存库位',
 lot_id VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '实际批次，无批次为NO_LOT',
 context_hash CHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '原任务及完整过账维度摘要',
 state VARCHAR(16) COLLATE utf8mb4_bin NOT NULL DEFAULT 'CLAIMED' COMMENT 'CLAIMED等待过账，PICKED已有原回执，RELEASED仅供明确补偿释放',
 active_serial VARCHAR(64) COLLATE utf8mb4_bin GENERATED ALWAYS AS (CASE WHEN state='RELEASED' THEN NULL ELSE serial_id END) STORED COMMENT '只对活跃占用执行唯一约束，补偿后仍保留原事实',
 version BIGINT NOT NULL DEFAULT 0 COMMENT '进度并发版本',
 created_at DATETIME(6) NOT NULL COMMENT '首次选择UTC时刻',
 updated_at DATETIME(6) NOT NULL COMMENT '最后进度UTC时刻',
 PRIMARY KEY(id),
 UNIQUE KEY uk_serial_pick_command(enterprise_id,warehouse_id,command_id,serial_id),
 UNIQUE KEY uk_serial_pick_active(enterprise_id,warehouse_id,sku_id,owner_epoch,active_serial),
 KEY idx_serial_pick_line(enterprise_id,warehouse_id,document_line_id,state,id),
 CONSTRAINT ck_serial_pick_state CHECK(state IN ('CLAIMED','PICKED','RELEASED')),
 CONSTRAINT ck_serial_pick_version CHECK(owner_epoch>=0 AND version>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='来源逐序列拣货占用及原过账回执，不以桶数量替代身份';
